export const data =[
    //graphs
    {
        question: "Consider a directed graph with n vertices and m edges such that all edges have same edge weights. Find the complexity of the best known algorithm to compute the minimum spanning tree of the graph?",
        option1:"O(m+n)",
        option2: "O(m logn)",
        option3:"O(mn)",
        option4:"O(nlogm)",
        ans: 1,
    },
    {
        question: "Consider a segment tree built on an array of N elements. What is the minimum number of node updates required to rebuild the entire tree if the original array is reversed?",
        option1:"N",
        option2: "N-1",
        option3:"2N-1",
        option4:"NlogN",
        ans: 3,
    },
    {
        question: "You are given a graph containing n vertices and m edges and given that the graph doesn’t contain cycle of odd length. Time Complexity of the best known algorithm to find out whether the graph is bipartite or not is ?",
        option1:"O(m+n)",
        option2: "O(1)",
        option3:"O(mn)",
        option4:"O(n^2)",
        ans: 2,
    },
    {
        question: "Let G be a simple graph with 20 vertices and 8 components. If we delete a vertex in G, then number of components in G should lie between ____.",
        option1:"8 and 20",
        option2: "8 and 19",
        option3:"7 and 19",
        option4:"7 annd 20",
        ans: 3,
    },
    {
        question: "Let G be the graph with 100 vertices numbered 1 to 100. Two vertices i and j are adjacent if |i−j|=8 or |i−j|=12. The number of connected components in G is",
        option1:"8",
        option2: "4",
        option3:"12",
        option4:"25",
        ans: 4,
    },
    {
        question: "Which of the following data structure is useful in traversing a given graph by breadth first search?",
        option1:"Stack",
        option2: "List",
        option3:"Queue",
        option4:"None of the above",
        ans: 3,
    },
    {
        question: "Consider an undirected unweighted graph G. Let a breadth-first traversal of G be done starting from a node r. Let d(r, u) and d(r, v) be the lengths of the shortest paths from r to u and v respectively, in G. lf u is visited before v during the breadth-first traversal, which of the following statements is correct?",
        option1:"d(r, u) < d (r, v)",
        option2: "d(r, u) > d(r, v)",
        option3:"d(r, u) <= d (r, v)",
        option4:"None of the above",
        ans: 3,
    },
    {
        question: "How many undirected graphs (not necessarily connected) can be constructed out of a given set V= {V 1, V 2,…V n} of n vertices ?",
        option1:"n(n-l)/2",
        option2: "2^n",
        option3:"n!",
        option4:"2^(n(n-1)/2)",
        ans: 4,
    },
    {
        question: "Consider an undirected random graph of eight vertices. The probability that there is an edge between a pair of vertices is 1/2. What is the expected number of unordered cycles of length three?",
        option1:"1/8",
        option2: "1",
        option3:"7",
        option4:"8",
        ans: 3,
    },
    {
        question: "What is the maximum number of edges in an acyclic undirected graph with n vertices?",
        option1:"n-1",
        option2: "n",
        option3:"n+1",
        option4:"2n-1",
        ans: 1,
    },
    
];